# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9a6620c9ad8361031f7cb8b408e1f27296426c5591fc84ad6641b0c1af5140c6dc8db6bf093c17e8bf5b45a9f31dfe6d3e24993333aa52f9b1bbe33784ce77ef

test:
  secret_key_base: ea20d8da4799edfbfdb4ea36ec122eaa2b7d0497dab63c79b953ca17da245a99d6ad7cf38978c04c153822c952c7c8b8ad2a2f3928ed7ae4d7341309cd3480a8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
