# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 40d1e4d882f2a969b88b1201b2253da19e52db90c0f0dbde04c67142a84625fe1a175c1a6fec620ff99e2278a1755b33dffb130f555a1171b54f350c0da5a989

test:
  secret_key_base: 604a5f25d28bf1f8dc61ac5d283adce3a8c5fae431cd4bbd447c4b48628346c6b8ba38fe13e33d7fdae4e273810d121bc5996097342383c94c1a8be9cbd31465

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
